# Ansible's apt module requires aptitude and python-apt. The two tasks below fix that.
- name: Do we have aptitude?
  stat: path=/usr/bin/aptitude
  register: aptitude_stat

- name: Ensure that requirements for the apt action are present
  shell: apt-get update && apt-get install -y python-apt aptitude
  when: not aptitude_stat.stat.exists

- name: apt-get update/upgrade
  apt: update_cache=yes upgrade=yes cache_valid_time=3600

- name: Ensure required packages are present
  apt: "name={{ item }} state=present"
  with_items: "{{ common_required_packages + common_extra_packages }}"
